### ISSUE TITLE
Doxygen consistency

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#1075]
Current doxygen description style varies with parameters `param`, `params`, `param[in/out]` and return values `return`, `returns`. 
Lets make it consistent.

**Comment by zhoonit** [comment]
For param, can we stick to `param` over `param[in/out]`?

1. 95% we return actual value instead of error code. 
1. For those 5% cases, in c++, `in` and `out` must be guess-able by const-correctness
1. there are supports for auto generation of `param` but not `param[in/out]` (because ide does not know it's in/out)

**Comment by kparichay** [comment]
> 95% we return actual value instead of error code.
> For those 5% cases, in c++, in and out must be guess-able by const-correctness

I am not sure but are you mixing return values with param[out]?

`param[in/out]` gives more readable information, and makes it easier to reason with the code. It also gives hints if the argument must be const or reference etc. `param` can be auto generated, and then `in/out` can be added manually.

**Comment by zhoonit** [comment]
> I am not sure but are you mixing return values with param[out]?

95% we return values instead of using outparams.

I mean we shouldn't reason by outparam then non-const but rather reason that non-const _is_ outparam in c++ for most of the cases. So, stating [out] a redundant comment that has no information for most of the cases.

If you think we should keep this, how about we leave it as an option as it is?

**Comment by kparichay** [comment]
> So, stating [out] a redundant comment that has no information for most of the cases.

even in the current code, many objects are non-const. They are being treated as `param[in]` but they are modified. Best example is `setProperty()`. Adding `out` to param just makes it more explicit.

> If you think we should keep this, how about we leave it as an option as it is?
> Or use only param and param[out] ?

Leaving out as an option brings out the inconsistency which is the purpose of this issue.
`param` and `param[out]` vs `param[in]` and `param[out]` are just equivalent. 
Supporting `in/out` or just plain params, either works, as long as it is consistent.

**Comment by zhoonit** [comment]
Cool. Let's go with `param` and `param[out]`.
