### ISSUE TITLE
[ Proposal ] Plug-able & Modularize Layer   

### ISSUE THREAD

**Issue by jijoongmoon** [nnstreamer/nntrainer#152]
Make Layer Plugable & Modularize to be able to re-configure at compile time

**Comment by kparichay** [comment]
Extend this to compile a layer individually as a shared object, and nntrainer can take a path to load all such layers.
Direct use case is external layers - so that external layers don't have to shipped directly with nntrainer but can still be supported if needed.
Check https://github.com/nnstreamer/nntrainer/pull/693#discussion_r517718088 thread for more.
