### ISSUE TITLE
Random in nntrainer

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#167]
random() returns random value in nntrainer.
This results in the indeterministic training of the models in the unit tests.

How about fixing the seed in testing so that we can ensure that the training result stays the same with newer changes.

@jijoongmoon please advise if there should be an API function for this?

**Comment by zhoonit** [comment]
Setting seeds seems great idea to me (also related to #133 )
Could you check if setting seeds would make a reproducible result as well?
I am concerning that since `databuffer` is designed to run concurrently, calling order of `random()` is not deterministic.

**Comment by kparichay** [comment]
@zhoonit Yes, #133 is good and is definitely needed.
Thanks for your input, I was not very familiar with `databuffer`, I will check the corresponding files and then update this issue.

**Comment by jijoongmoon** [comment]
Well, some example ( not all includes backwarding )is already included in #148. This python code is generate the input and output. golden data. and compared with output from nntrainer. (Tensorflow is used to generate the golden data). However, we do not have tensorflow for tizen so that tar file is used.

**Comment by kparichay** [comment]
Current major issue is initialization. I will for now make the seed fixed. 
Later, maybe add an interface for user to set it.
