### ISSUE TITLE
Support multiple outputs and multiple out connections for a layer

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nntrainer#1706]
Current implementation limits all the outputs of a layer to be sent to the output nodes. However, that is not always the desired case. Consider the example below:
```
In -> Layer A -> out1, out2
out1 -> Layer B
out2 -> Layer C
```

This kind of graph is not supported as of now and must be supported.

Further, there is inconsistency between the routing of the nodes output. In split layer, each outputs is passed to individual layer, but in multiout layer, all the inputs are passed to all the layers. This also needs to be resolved.

**Comment by kparichay** [comment]
There are two solutions:

1. Routing Layer
Routing layer will take n inputs and route these n inputs to n layers. As routing layer will only perform routing of the tensors, both forwarding and backwarding will always be no-op and routing layer can always work in-place.
Routing layer will not support routing an input to multiple layers (this must be done with multiout layer). The inputs of the routing layer can be from 1 layer or multiple layers.

2. Update the graph 
This requires updating the graph nodes and connections to allow multiple tensors to flow over a connection. This implies that `numInputConnections <= numInputTensors` and will require changes in the core of NetworkGraph and LayerNode.

**Comment by zhoonit** [comment]
Let's consider a case where

A outputs a1, a2
B outputs b1
C needs a1, b1
D needs a2

1. naive router idea

```ini
[layer A]
type=will_have_two_outputs

[layer B]
type=will_have_one_output

[router]
type=router
input_layers=layer A, layer B
routed_to=layer C, layer D, layer C

[layer C]
type=need_two_inputs
input_layers=router

[layer D]
type=need_one_inputs
input_layers=router
```

In this case, we need to propagate `routed_to` to layer node, because graph needs to query which implies that this has to be global property for everyone, which means it will be able to do like below.

Anyway, IMO, the takeaway here is that the connection information can't stay inside a layer, so that even if we make a router layer it won't be any time saver.

2. router idea with global property

So below idea should be valid, and more concise.

```ini
[layer A]
type=will_have_two_outputs
route_to=layer_c, layer_d

[layer B]
type=will_have_one_output
route_to=layer_c

[layer C]
type=need_two_inputs
input_layers=layer A, layer B

[layer D]
type=need_one_inputs
input_layers=layer A
```

I think this option is likely to make some mistake as there is a two pairs should match (route_to / input_layers)


3. routing from input_layers directly.

```ini
[layer A]
type=will_have_two_outputs

[layer B]
type=will_have_one_output

[layer C]
type=need_two_inputs
input_layers=layer A:0, layer B:0

[layer D]
type=need_one_inputs
input_layers=layer A:1
```

with this setup it will be more concise and more readable.

**Comment by jijoongmoon** [comment]
I think the keywords need to be changed later for the case 3. %s/input_layers/ inputs/
and I wonder if we need to set the type even. We can realize with the info from children's inputs.

**Comment by kparichay** [comment]
As discussed offline, the user-interface can be multiple and the one described at  https://github.com/nnstreamer/nntrainer/issues/1706#issuecomment-969839564 looks good. 

There needs to be fixed semantics about the number of tensors that can flow over each edge between nodes (layers) in the graph. For now, we have fixed it to be 1 tensor per edge in the graph.

**Comment by zhoonit** [comment]
workout plan -

1. Multiout before setting output
2. Add & parse index information
