### ISSUE TITLE
Tizen 7.0 build

### ISSUE THREAD

**Issue by eightreal** [nnstreamer/nntrainer#2337]
Hello, I'm try to use gbs to build the nntrainer , I follow your docs but it report the error
```
No source package found at ...
<gbs> some package failed to be built
```

I'm try to write a native DrL app (follow your dqn code)for tizen-7.0 aarch64.
Is there any another method to use the nnstrain (for example: add buildRequires?)

Thanks for your help

**Comment by eightreal** [comment]
收到，谢谢

**Comment by myungjoo** [comment]
Provide more information on what you have tried so that others can reproduce the results.

If you are using gbs, you need to share your gbs configuration, the gbs command you use, the path you are using in (and how you've got the path for gbs), more outputs from gbs, and so on.

Anyway, are you new to gbs or Tizen development?
Do you also aware that, by using gbs, you are actually developing the os (and its middleware/service), not the app?

**Comment by myungjoo** [comment]
The most recommended way to access nntrainer for Tizen applications is to access via Tizen ML API.

**Comment by myungjoo** [comment]
```
No source package found at ...
<gbs> some package failed to be built
```

This means that the directory ```...``` is not nntrainer.git or any other valid Tizen package git. or you have some access control issue in your file system.

Even in an empty git repo with a single file ```./packaging/name.spec```, you don't get such an error.

**Comment by eightreal** [comment]
Yes, it always occurs on this status .
But my gbs conf can compile other packages successfully. 

And as you said use rpm released  ,could your help provided some method. I try the requirepackage method as my mail said.but it report can't find 'tensor_dim.h',

Do I need add other require package?

**Comment by eightreal** [comment]
Yes ,I agree with you ,the error looks like not find a spec file, but I can compile  my package with the gbs conf

And ,as you said use ml api method, could you help provide more information, as I add requires pkgconfig nntrainer, I can' t find the nntrainer headline in my gbs build root.

**Comment by myungjoo** [comment]
> Yes ,I agree with you ,the error looks like not find a spec file, but I can compile my package with the gbs conf

So, show me the command sequence (and its outputs) to reproduce what you get from a clean Ubunto.

I've never seen such an error from any legit Tizen-compliant git since pre-Tizen 1.0.

Otherwise, I can only say that you are running gbs on a non-legit git repo, on a directory without .spec file, on a broken file system, or with a file access issue. 

(do ```$ mkdir cleandir && cd cleandir && git clone https://github.com/nnstreamer/nntrainer && cd nntrainer && gbs build```)

> 
> And ,as you said use ml api method, could you help provide more information, as I add requires pkgconfig nntrainer, I can' t find the nntrainer headline in my gbs build root.


Look at other packaging using nntrainer in Tizen. (use codegrok)

**Comment by eightreal** [comment]
hello, I reinstall  my gbs ,now the issue is fix up! Thanks for your help very much.
