### ISSUE TITLE
Add `-Denable-fp16=true` build to CI

### ISSUE THREAD

**Issue by heka1024** [nnstreamer/nntrainer#2560]
Some code could break build with `-Denable-fp16=true` option, like https://github.com/nnstreamer/nntrainer/pull/2545. I think it would be helpful to add this build to CI to ease the burden on reviewers.

**Comment by heka1024** [comment]
@skykongkong8 What do you think?

**Comment by skykongkong8** [comment]
Good point.
As far as I am concerned, Reason why `-Denable-fp16` is not included in current CI is because it is relatively newer option than the others.
Even for now, I personally think that it is not really matured to be checked for every PR, because we have multiple plans to refactorize the structure of half-precision formats. I need more opinions about this. @jijoongmoon

**Comment by myungjoo** [comment]
You may add enable-fp16 build test in CI.
You may limit test coverage or error reporting mechanisms for enable-fp16, too. (you can let github-action gracefully ignore failed TCs, too, so that we can see the number of failed cases but the CI says "OK".)

Anyone needing this may add it.

**Comment by heka1024** [comment]
@skykongkong8 @myungjoo I'll add this to CI. Thanks for comment!

**Comment by skykongkong8** [comment]
Great! Thanks for pointing this issue out :)
