### ISSUE TITLE
Tensor default dimension & allocation

### ISSUE THREAD

**Issue by jijoongmoon** [nnstreamer/nntrainer#359]
Default tensor construct should have empty buffer. However currently we have 1:1:1:1 tensor and allocate one buffer.

**Comment by zhoonit** [comment]
This is not bug actually a feature.

Allowing zero dimension would IMO cause more harm than good

**Benefit**
1. you can make a `null` tensor that saying, 'I am nothing' which can and should be altered in better ways.
2. you do not have to allocate a memory buffer of size 1 which in most of the case only cause negligible overhead since you are not gonna make whole bunch of empty tensor. 

**Harm**
1. You have to verify tensordim when it need not be 0. (basically reverting patch made in https://github.com/nnstreamer/nntrainer/pull/234/commits/7a70a1fcc85b1f676171fe667852470c203feeac).
2. If not, the code cause bugs... and those bugs are so hard to catch. (for eg, `fc_layer` was initially had unit of `0` and causing bugs which was so hard to catch.)
3. Null is just not allowed, so making artificial null does not sound right like in java (https://dzone.com/articles/code-smells-null) 
what if empty tensor propagates and set tensor batch of 3. It cause bugs will not throw in the right spot.

Rather, we should explicitly declare the place we need to use empty tensor only use within that scope only.

**Suggested alternatives**
1. Use `std::optional` or equivalent
2. Using empty static Tensor variable

**Comment by kparichay** [comment]
@zhoonit 
Allowing default dimensions of 1 also has its own cons.
1. Forgetting to set the tensorDim now proceeds the model without any error, and later causes segmentation faults just as same as default dimension is 0.
2. Allocation of memory considering overhead isn't a lot. However, the unnecessary allocation and de-allocation of memory can cause overheads for backends like GPUs and NPUs.

IMO, verification of tensorDim still has to be done for each operation whether a particular dimension is matching/valid.
Regarding setting a particular dimension (like `tensor.batch(5)`) can reset all the zero dimensions with 1.
Overall, setting default dimensions to 0 just affects the case where the default constructed tensor is used without setting any dimension.

`std::optional` solves the problem when `Tensor` has to be passed as a default argument. However, it does not solve the issue of the default constructor which happens a lot in our repository.

**Comment by zhoonit** [comment]
> 🍰 Forgetting to set the tensorDim now proceeds the model without any error, and later causes issues just as same as default dimension is 0. Setting dimension 0 might be easier to debug as its memory would be NULL, compared to 1 where memory is just of size 1 and user

I think it is reasonable that if someone omit a dimension, it should be 1 not 0. Still, we can define this to be invalid (like in :cake: case). Then we shouldn't allow that in the first place by not exposing default constructor. So compiler can check before program bump into segfault. We can check it because we defined the behavior as invalid without checking memory.

e.g.) if you put nothing in numpy, it is assumed scalar value (that was my intention.)
But if you put really nothing, it raise a checked exception.
``` python
> import numpy as np
> x = np.array(None)
> print(x.size)
1
> print(x.item())
None
```

```python
> import numpy as np
> x = np.array() #this raise an error.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/usr/local/bin/start_ipython.py in <module>
----> 1 x = np.array()

TypeError: array() missing required argument 'object' (pos 1)
```

> :carrot: However, the unnecessary allocation and de-allocation of memory can cause overheads for backends like GPUs and NPUs.

For :carrot:, allocating memory when constructing an instance is not an overhead but should be intended at all cases. Which I think, 
🌵 is not common as well. If I understood correct, it sounds like initiate an object to NULL when construct and initialize when setting a property.

> 🌵 IMO, verification of tensorDim still has to be done for each operation whether a particular dimension is matching/valid.
Regarding setting a particular dimension (like tensor.batch(5)) can reset all the zero dimensions with 1.
Overall, setting default dimensions to 0 just affects the case where the default constructed tensor is used without setting any dimension.

> :cd: std::optional solves the problem when Tensor has to be passed as a default argument. However, it does not solve the issue of the default constructor which happens a lot in our repository.

:cd: actually has my point. If we use "0:0:0:0" as a NULL, how can we tell if given `Tensor` is intended to be empty(because it is allowed to) or just from a buggy behavior? 

eg)

```cpp
  Tensor t();

  t.batch(5); // should this be error? or okay? we are not sure if t is null Tensor so this should be invalid or just on the way of *constructing* the tensor
```

Of course allocating memory to NULL can be overhead. so If we are not going to use monadic operation like `std::optional`, we should do sth like:

```cpp
class Tensor{
public:
    static Terson Empty(){
// could be singleton and return reference as well. anyway concept stays the same
        return Terson();
    }
private:
    Terson() = default; /** with indicating Tensor is empty, dimension can be used, a bit flag can be used */
};

int main()
{
    Tensor empty_tensor = Tensor::Empty(); 
}
```

**Comment by kparichay** [comment]
> I think it is reasonable that if someone omits a dimension, it should be 1, not 0.

Providing any of the dimensions as non-zero would initialize the unknown dimensions to 1. However, not knowing any dimension would set all dimensions 1. For example - Tensor(2), Tensor(1,2), Tensor(1,1,2) and Tensor(1,1,1,2) would all be equivalent. 
So omitting a dimension would result in 1 and not 0.

However, Tensor() would generate dimension (0,0,0,0) as all the dimensions are unknown and no need to give it any size/memory.

The primary reason is to avoid allocation of memory when ever developer uses default Tensor constructor. So, either default constructor is disabled or it does not allocate any memory.

> If we use "0:0:0:0" as a NULL, how can we tell if given Tensor is intended to be empty(because it is allowed to) or just from a buggy behavior?

if a given Tensor is empty, then its intended. It can be buggy but that's what was sent. 

> Tensor t();
>  t.batch(5); 

This wont be an error as explained above.

> If I understood correct, it sounds like initiate an object to NULL when construct and initialize when setting a property.

If constructed without any property, then keep as NULL.

**Comment by zhoonit** [comment]
> So, IMO either default constructor should be disabled or it does not allocate any memory, as it is a relatively common behavior to first declare and then set property (dimension in this case).

Agreed. How about we delete default constructor for tensor and make a special NULL tensor (or equivalent function) so that we can make a comparison or use it as a default parameter if nullable?
