### ISSUE TITLE
 buf size is determined after minibatch size is set at load config

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#389]
+ batch seems not updated when loadConfig. please check this as well

**Comment by kparichay** [comment]
This can be the case where `Dataset` is loaded before `Model` from the ini.
Let's fix for the `Model` to be loaded first, then `Dataset` and then all the layers.

**Comment by zhoonit** [comment]
> This can be the case where `Dataset` is loaded before `Model` from the ini.
> Let's fix for the `Model` to be loaded first, then `Dataset` and then all the layers.

Isn't this resolved with a3f0ae4a20aa93470a505deb6f8e2f82dc3e47fb ?

**Comment by kparichay** [comment]
As you already know, since https://github.com/nnstreamer/nntrainer/commit/ab6dc9985f920591e86e2ddcfad64d5f3c8f0fee, it is possible that network, dataset and layers can be loaded in any order (depending on how the user specifies it in the ini model).
If the dataset is specified before the network, then batch size has been read from the ini file yet, which sets the wrong default value for the dataset buffer size.
IMO, the order of reading should be fixed. The model first, then dataset and then layers to overcome such issues in the future.
