### ISSUE TITLE
[Tensor] Add unified interface to deal with low level operations

### ISSUE THREAD

**Issue by zhoonit** [nnstreamer/nntrainer#701]
## As-Is
Currently, some tensor operation(namely, `layer` 🐨 ) is depending on tensor implementation 🐤 , which means that 🐨  should know about the 🐤 . 

## To-Be
🐨 shouldn't know about 🐤 rather there should be a way to abstract those always (direct memory accessing or others...)
As we are going to add another device, it will be crucial to decouple 🐨  from 🐤 

## What to Do

To decouple :koala: from 🐤  it should rely on unified interface to deal with low level( or memory level...? ) operation.

I think if we need a method suites including

  1. get an address (which is already there with `Tensor::getAddress`)
  2. `operator []` or `Tensor::at`
  3. something like memcpy or std::copy or std::reverse_copy and so on...
  4. Possibly allocators (but this is already there in c++ I think??)

and more

**Comment by kparichay** [comment]
Some objects using Tensor (Layer in this case) must know certain information about the implementation of Tensor and should not know about other certain ones.
Should know:
1. Tensor is a wrapper for the actual data, and this actual data can be shared with multiple tensors as is managed with `shared_ptr`.
2. Tensor is not deeply copied unless called with the method `clone`/`copy`
3. Data represented by Tensor is a 1-D contiguously allocated memory (always) on the device where it should be. The shape of a tensor provides n-D abstraction (n is limited to 4 for now) over the 1-D data
4. Tensor operations are out-of-place unless the method is suffixed with `_i`
5. Direct memory can be accessed with a pointer for reading/writing. However, the memory will always be managed by the tensor itself.

Given `3.`, `getAddress` or `[ ]` or `at` is a syntactic sugar. Just like std::vector clarifies that the memory is contiguous and can be addressed manually, the same rule applies here. The implementor should know about the memory details and must be able to access the memory directly as certain backends would require tackling with c-interface or needing `void *ptr` which is continuously addressed.

Providing some interface for the tensor to operate to decouple the two elements is good, but that doesn't mean that the user must know the tensor implementation to a certain degree (I listed out 5 points, maybe more can be needed) in order to be able to properly use it.

Also, note that with a unified interface, non-abstract access would still need to be provided.

**Comment by zhoonit** [comment]
> Providing some interface for the tensor to operate to decouple the two elements is good, but that doesn't mean that the user must know the tensor implementation to a certain degree

I totally agree that the user should know about the point you've mentioned. However, I rather think those points are _dependent preconditions_ mentioned in [here](https://abseil.io/blog/20180531-regular-types), not about the interface. 
My point is that user should have a unified access to the tensor which is not related to knowing _dependent precondition_.

For example, if user wanna copy the 5 data starting from Tensor `A.channel(5).getAddress()` to `B.channel(1).getAddress()` 

in CPU user might use `memcpy` However in cuda, user should use `cudaMalloc` or whatnot.
How user access the direct memory should be unified by defining the direct memory access.

**Comment by kparichay** [comment]
Right, so there are two kinds of operations - high level operations which are already supported and will be extended for other backends as needed.
For low level operations, support for CPU is easy to provide. However, extending to other HW/backends wont be that intuitive.
You can list the operations and start support for CPU, and then extend as much possible for other backends.

**Comment by zhoonit** [comment]
>  However, extending to other HW/backends wont be that intuitive.

Agreed. For now, it is just an idea worth or worth not trying later when we have to extend :p
