### ISSUE TITLE
MNIST: inference example to the implementation.

### ISSUE THREAD

**Issue by lekogabi** [nnstreamer/nntrainer#860]
Dear NNTrainer Team!

I am trying to add an inference to the MNIST example. The training is working well. My modifications can be found here:
https://pastebin.com/3Ebb6MX9

One way to run after the build:
./nntrainer_mnist inference ../res/mnist.ini mnist_trainingSet.dat

I followed the inference example from the LogisticRegression implementation, but unfortunately I cannot make it to work.

Could you please take a look at it and give me some hints how to make some corrections, or could you provide a simple inference example to the MNIST implementation?

Thanks in advance!

Regards,
Gabor Leko

**Comment by kparichay** [comment]
@lekogabi Thanks for the issue, I will take a look at it and report back today.

**Comment by kparichay** [comment]
I tried the code you shared. The code ran successfully but there was a warning by the `cblas_sgemm`

```bash
** On entry to SGEMM  parameter number  3 had an illegal value
```

This is because the input data you are using is not of the appropriate shape.  In the MNIST model, the convolution layer expects a 2D input, however, the input provided is a 1-D input. To solve this, please apply the below change to your application code:

```diff
-auto answer = NN->inference({MAKE_SHARED_TENSOR(nntrainer::Tensor({o}))});
+nntrainer::Tensor T =nntrainer::Tensor({o});
+T.reshape({1,1,28,28});
+auto answer = NN->inference({MAKE_SHARED_TENSOR(T)});
```

`Convolution layer` does not perform shape checks only at compile time and not at runtime for optimization purposes.
In the current implementation, the `input layer` does not reshape the layer directly as in certain cases, reshape is not enough and transpose is required.

Please try this and let me know if your problem is resolved.

**Comment by kparichay** [comment]
#864 will log the error and return empty output in case of input dimension mismatch in inference.

**Comment by lekogabi** [comment]
Hi,
Thank you. It solved my problem.
Gabor
